### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by citronalco** [g7/droid-compat-f5321#1]
This project sounds quite interesting! How do I use this on the phone- if it's already usable?
Could you provide a small howto?

**Comment by g7** [comment]
Hello!

Yes, it's already usable, I'm using it as my daily driver since ~3 months and I don't have major issues with it (at least, nothing that I didn't have with the custom-built 2.1.2 build that I was using before).
It even survived two OTA upgrades (2.1.3 -> 2.1.4 -> 2.2.0), so I'm pretty satisfied.

The only drawbacks are that OTG is not supported (the Xperia X kernel does not supply the driver for the Type-C controller in the X Compact) and currently some secondary sensors are disabled (this will be reverted once I singled out the misbehaving sensor that makes the battery drain - but I didn't have the time to debug it yet).

An official Sailfish X for F5121 (Xperia X Single Sim) image is required, with a valid license in order to install Android Support and the like.

Unfortunately another piece (the image patcher) is not yet public as I'm not currently satisfied with the code. I'm refactoring it a bit, albeit slowly. A bit more of patience is needed :)

Please tell me if you want to beta test once I prettied-up the code. I do not have the time currently to reflash my device, which is also my daily driver, so development is also slowed up for this reason (other than a generic lack of time).

So far two devices are working nicely, one which started with 2.1.3 (mine) and one with 2.1.4 (a friend's). It would be great to try with 2.2.0 now that the images are available on the Jolla shop :)

The patcher does work only on Linux machines.

**Comment by citronalco** [comment]
Sounds great! I have a spare Sony Xperia X Compact (currently with the community build from here: https://together.jolla.com/question/180109/announcement-community-sony-xperia-x-compact-release/) , a Linux machine and I'm going to buy Sailfish X to give your patcher a try with 2.2.0. I don't care if things get a little messy and I won't become desperate if it doesn't work at all, so you don't have to polish your code too much. Just let me know.

**Comment by g7** [comment]
Nice! Please fire up a mail to me   -  at  -  medesimo  - dot -  eu so that I can send the current patcher version.

**Comment by g7** [comment]
Will leave this issue open until the patcher repository is public :)

**Comment by g7** [comment]
Patcher now available at https://github.com/g7/sailfishx-patcher-f5321

Thanks for helping testing this thing out, @citronalco - I can finally close this issue :)
